language: ruby
rvm:
  - 2.2.2
  - 2.3.0
script: bundle exec rake spec
gemfile:
  - gemfiles/rails3.gemfile
  - gemfiles/rails4_0.gemfile
  - gemfiles/rails4_1.gemfile
  - gemfiles/rails4_2.gemfile
  - gemfiles/rails5_0.gemfile
  - gemfiles/rails5_1.gemfile
notifications:
  email:
    - support@travellink.com.au
sudo: false
cache: bundler
